"""Provider-level constants for the Oddspapi pre-start odds flow."""

ODDSPAPI_SOURCE = "oddspapi"
ODDSPAPI_INGESTION_SOURCE = "oddspapi_pre_start"
ODDSPAPI_CURRENT_ODDS_ENDPOINT = "odds"
ODDSPAPI_HISTORICAL_ODDS_ENDPOINT = "historical-odds"
ODDSPAPI_PRE_START_ODDS_ENDPOINTS = frozenset(
    {
        ODDSPAPI_CURRENT_ODDS_ENDPOINT,
        ODDSPAPI_HISTORICAL_ODDS_ENDPOINT,
    }
)
DEFAULT_ALLOWED_MARKET_GROUPS = None
DEFAULT_ALLOWED_MARKET_PERIODS = None
DEFAULT_ALLOWED_MARKET_KEYS = None
